"""
Constant definitions.
"""


__all__ = [
    "GLOBAL_SCOPES",
    "ET_SCOPES",
    "MT_SCOPES",
    "TT_SCOPES",
    "EM_SCOPES",
    "EE_SCOPES",
    "MM_SCOPES",
    "ELECTRON_SCOPES",
    "MUON_SCOPES",
    "SL_SCOPES",
    "FH_SCOPES",
    "FL_SCOPES",
    "HAD_TAU_SCOPES",
    "SCOPES",
    "ERAS",
]


# all scopes containing hadronic taus
GLOBAL_SCOPES = ["global"]
ET_SCOPES = ["et"]
MT_SCOPES = ["mt"]
TT_SCOPES = ["tt"]
EM_SCOPES = ["em"]
EE_SCOPES = ["ee"]
MM_SCOPES = ["mm"]
ELECTRON_SCOPES = ET_SCOPES + EM_SCOPES + EE_SCOPES
MUON_SCOPES = MT_SCOPES + EM_SCOPES + MM_SCOPES
SL_SCOPES = ET_SCOPES + MT_SCOPES
FH_SCOPES = TT_SCOPES
FL_SCOPES = EM_SCOPES + EE_SCOPES + MM_SCOPES
HAD_TAU_SCOPES = SL_SCOPES + FH_SCOPES
SCOPES = HAD_TAU_SCOPES

ERAS = ["2016preVFP", "2016postVFP", "2017", "2018"]
