// Fixture-driven boundary test for xyh::object_selection::tight_jet_id_2018_puppi_v15.
//
// This is a standalone (non-CROWN-generated) executable: it builds a
// single-jet ROOT::RDataFrame for every boundary case pinned in
// tests/fixtures/jetid_2018UL_puppi_tight_v1.json (via the generated
// jetid_fixture.inc, see run_jetid_test.sh), applies the producer function
// directly, and asserts the resulting mask against the fixture's
// `expected_pass`. Cases with `expected_pass: null` are out-of-scope
// markers and are skipped already at fixture-generation time (see
// run_jetid_test.sh), so every case that reaches this file must be
// checked.
//
// Run via: bash tests/cpp/run_jetid_test.sh (from the analysis directory,
// inside the CROWN container -- see that script for the compile command).

#include "jetid_v15.hxx"

#include <ROOT/RDataFrame.hxx>
#include <ROOT/RVec.hxx>
#include <cstddef>
#include <cstdlib>
#include <iostream>
#include <string>

// Generated by run_jetid_test.sh from the fixture JSON; defines
// `JetIDFixtureCase`, `kFixtureFormulaVersion`, `kFixtureCases`, and
// `kFixtureCasesCount`.
#include "jetid_fixture.inc"

namespace {

// Build a one-event, one-jet RDataFrame for a single fixture case and
// return the boolean mask entry produced by the function under test.
int evaluate_case(const JetIDFixtureCase &c) {
    ROOT::RDataFrame df(1);

    auto df1 =
        df.Define("Jet_eta",
                  [&c]() { return ROOT::RVec<float>{c.eta}; })
            .Define("Jet_neHEF",
                    [&c]() { return ROOT::RVec<float>{c.neHEF}; })
            .Define("Jet_neEmEF",
                    [&c]() { return ROOT::RVec<float>{c.neEmEF}; })
            .Define("Jet_nConstituents",
                    [&c]() {
                        return ROOT::RVec<UChar_t>{
                            static_cast<UChar_t>(c.nConstituents)};
                    })
            .Define("Jet_chHEF",
                    [&c]() { return ROOT::RVec<float>{c.chHEF}; })
            .Define("Jet_muEF",
                    [&c]() { return ROOT::RVec<float>{c.muEF}; })
            .Define("Jet_chEmEF",
                    [&c]() { return ROOT::RVec<float>{c.chEmEF}; })
            .Define("Jet_chMultiplicity",
                    [&c]() {
                        return ROOT::RVec<UChar_t>{
                            static_cast<UChar_t>(c.chMultiplicity)};
                    })
            .Define("Jet_neMultiplicity", [&c]() {
                return ROOT::RVec<UChar_t>{
                    static_cast<UChar_t>(c.neMultiplicity)};
            });

    ROOT::RDF::RNode node = df1;
    auto df2 = xyh::object_selection::tight_jet_id_2018_puppi_v15(
        node, "mask", "Jet_eta", "Jet_neHEF", "Jet_neEmEF",
        "Jet_nConstituents", "Jet_chHEF", "Jet_muEF", "Jet_chEmEF",
        "Jet_chMultiplicity", "Jet_neMultiplicity");

    auto masks = df2.Take<ROOT::RVec<int>>("mask").GetValue();
    return masks.at(0).at(0);
}

} // namespace

int main() {
    int exit_code = 0;

    // formula_version cross-check: the header's pinned constant must match
    // the fixture's "formula_version" field exactly.
    if (std::string(xyh::object_selection::formula_version) !=
        std::string(kFixtureFormulaVersion)) {
        std::cerr << "FAIL formula_version mismatch: header='"
                  << xyh::object_selection::formula_version
                  << "' fixture='" << kFixtureFormulaVersion << "'"
                  << std::endl;
        return 1;
    }
    std::cout << "formula_version OK: "
              << xyh::object_selection::formula_version << std::endl;

    int failures = 0;
    for (std::size_t i = 0; i < kFixtureCasesCount; ++i) {
        const JetIDFixtureCase &c = kFixtureCases[i];
        int actual = evaluate_case(c);
        bool ok = (actual == c.expected);
        std::cout << (ok ? "PASS " : "FAIL ") << c.name
                  << " expected=" << c.expected << " actual=" << actual
                  << std::endl;
        if (!ok) {
            ++failures;
        }
    }

    if (failures > 0) {
        std::cerr << failures << " of " << kFixtureCasesCount
                  << " case(s) FAILED" << std::endl;
        exit_code = 1;
    } else {
        std::cout << "All " << kFixtureCasesCount
                  << " boundary cases PASSED." << std::endl;
    }

    return exit_code;
}
