// Fixture-driven test for
// xyh::scalefactor::btagging_strict::multi_wp_event_weight.
//
// A standalone (non-CROWN-generated) executable that drives the strict
// UParTAK4 fixed-multi-WP b-tag event-weight consumer against synthetic
// correctionlib fixtures (tests/fixtures/btag_sf_strict_{sf,eff}.json,
// generated by tests/fixtures/make_btag_sf_strict_fixtures.py).
//
// Cases:
//   (a) nominal weight reproduces a hand-computed value;
//   (b) efficiency <= 0 -> throws;
//   (c) non-monotonic efficiencies -> throws;
//   (d) comb-only variation (up_hf) changes b/c jets, leaves light central
//       (mixed-flavor event);
//   (e) unsupported variation key -> throws;
//   (f) jet passing the TIGHTEST WP (XXT) -> jet_w == SF(XXT), the eff-cancel
//       branch of the algebra;
//   (g) jet failing ALL WPs (score below the loosest, L) -> jet_w ==
//       (1 - SF(L)*eff(L)) / (1 - eff(L)), the untagged-probability branch;
//   (h) efficiency > 1 -> throws;
//   (i) a jet flavor outside {0, 4, 5} -> throws.
//
// The WP score thresholds are not passed in: the consumer reads them from the
// SF payload's UParTAK4_wp_values correction, which the fixture generator
// fills with (tightest -> loosest) {XXT: 0.9, XT: 0.7, T: 0.5, M: 0.3,
// L: 0.1} -- the thresholds every case below assumes.
//
// Run via: bash tests/cpp/run_btag_sf_test.sh (which regenerates the fixtures
// first; see that script for the compile command).

#include "btag_sf_strict.hxx"

#include "utility/CorrectionManager.hxx"

#include <ROOT/RDataFrame.hxx>
#include <ROOT/RVec.hxx>
#include <cmath>
#include <exception>
#include <functional>
#include <iostream>
#include <string>
#include <vector>

#ifndef BTAG_FIXTURE_SF
#define BTAG_FIXTURE_SF "tests/fixtures/btag_sf_strict_sf.json"
#endif
#ifndef BTAG_FIXTURE_EFF
#define BTAG_FIXTURE_EFF "tests/fixtures/btag_sf_strict_eff.json"
#endif

namespace {

int g_failures = 0;

// Relative-tolerance float comparison for the hand-computed algebra.
bool approx_equal(double a, double b, double tol = 1e-6) {
    if (a == b) {
        return true;
    }
    double denom = std::abs(a) + std::abs(b);
    if (denom == 0.0) {
        return true;
    }
    return std::abs(a - b) / denom < tol;
}

void check(bool ok, const std::string &name) {
    std::cout << (ok ? "PASS " : "FAIL ") << name << std::endl;
    if (!ok) {
        ++g_failures;
    }
}

template <typename T>
ROOT::RVec<T> mkvec(const std::vector<T> &values) {
    ROOT::RVec<T> out;
    for (const auto &value : values) {
        out.push_back(value);
    }
    return out;
}

// Run the strict consumer on a single (possibly multi-jet) event and return
// the event weight. May throw (the strict consumer rejects degenerate input).
double run_weight(correctionManager::CorrectionManager &mgr,
                  const std::vector<float> &pt, const std::vector<float> &eta,
                  const std::vector<int> &flavor,
                  const std::vector<float> &score, const std::vector<int> &mask,
                  const std::string &eff_sample_type,
                  const std::string &variation_comb,
                  const std::string &variation_light) {
    ROOT::RDataFrame df(1);
    auto defined =
        df.Define("Jet_pt", [pt]() { return mkvec(pt); })
            .Define("Jet_eta", [eta]() { return mkvec(eta); })
            .Define("Jet_flavor", [flavor]() { return mkvec(flavor); })
            .Define("Jet_score", [score]() { return mkvec(score); })
            .Define("Jet_mask", [mask]() { return mkvec(mask); });
    ROOT::RDF::RNode node = defined;
    auto out = xyh::scalefactor::btagging_strict::multi_wp_event_weight(
        node, mgr, "btag_weight_upart", "Jet_pt", "Jet_eta", "Jet_flavor",
        "Jet_score", "Jet_mask", BTAG_FIXTURE_SF, BTAG_FIXTURE_EFF,
        eff_sample_type, variation_comb, variation_light);
    return out.Take<double>("btag_weight_upart").GetValue().at(0);
}

bool throws(const std::function<void()> &fn) {
    try {
        fn();
        return false;
    } catch (const std::exception &) {
        return true;
    }
}

} // namespace

int main() {
    correctionManager::CorrectionManager mgr;

    // ------------------------------------------------------------------
    // (a) Nominal weight reproduces a hand-computed value.
    //
    // A single b-jet (flavor 5) with score 0.4 passes WP M (0.4 >= 0.3) but
    // not WP T (0.4 < 0.5), so it lands in the M/T bin:
    //     jet_w = (SF(M)*eff(M) - SF(T)*eff(T)) / (eff(M) - eff(T))
    // With the fixture "valid" efficiencies (flavor 5): eff(M)=0.60, eff(T)=0.40
    // and central comb SFs (flavor 5): SF(M)=0.95, SF(T)=0.90:
    //     jet_w = (0.95*0.60 - 0.90*0.40) / (0.60 - 0.40)
    //           = (0.57 - 0.36) / 0.20 = 0.21 / 0.20 = 1.05
    // Kept in scope: case (d) reuses it as its b-only central reference.
    // ------------------------------------------------------------------
    const double w_bonly_cc = run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.4f},
                                         {1}, "valid", "central", "central");
    check(approx_equal(w_bonly_cc, 1.05),
          "(a) nominal weight == hand-computed 1.05");

    // ------------------------------------------------------------------
    // (b) An efficiency <= 0 must throw (no silent 1.0 substitution). The
    // "zero" regime sets flavor-5 eff(M) = 0.
    // ------------------------------------------------------------------
    {
        bool did_throw = throws([&]() {
            run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.4f}, {1}, "zero",
                       "central", "central");
        });
        check(did_throw, "(b) efficiency <= 0 throws");
    }

    // ------------------------------------------------------------------
    // (c) Non-monotonic efficiencies must throw. The "nonmono" regime sets
    // flavor-5 eff(M)=0.30 < eff(T)=0.50, so the M/T bin has a non-positive
    // denominator.
    // ------------------------------------------------------------------
    {
        bool did_throw = throws([&]() {
            run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.4f}, {1}, "nonmono",
                       "central", "central");
        });
        check(did_throw, "(c) non-monotonic efficiency throws");
    }

    // ------------------------------------------------------------------
    // (d) A comb-only component (up_hf) changes b/c jets while leaving light
    // jets central. Mixed event: one b-jet (flavor 5, score 0.4) and one light
    // jet (flavor 0, score 0.15). Dispatch: variation_comb="up_hf",
    // variation_light="central".
    //
    // The event weight factorizes over jets, so comparing the mixed-event
    // (up_hf)/(central) ratio against the b-only one covers both halves of the
    // claim in two assertions: they can only agree if the light factor
    // cancels, i.e. is unchanged by the comb-only component, and the ratio
    // differing from 1 shows the b-jet really did change. The b-only central
    // weight is case (a)'s.
    // ------------------------------------------------------------------
    {
        double w_mixed_cc = run_weight(mgr, {50.0f, 60.0f}, {1.0f, 1.2f},
                                       {5, 0}, {0.4f, 0.15f}, {1, 1}, "valid",
                                       "central", "central");
        double w_mixed_uc = run_weight(mgr, {50.0f, 60.0f}, {1.0f, 1.2f},
                                       {5, 0}, {0.4f, 0.15f}, {1, 1}, "valid",
                                       "up_hf", "central");
        double w_bonly_uc = run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.4f}, {1},
                                       "valid", "up_hf", "central");
        double ratio_mixed = w_mixed_uc / w_mixed_cc;
        double ratio_bonly = w_bonly_uc / w_bonly_cc;
        check(approx_equal(ratio_mixed, ratio_bonly),
              "(d) mixed-event variation ratio is entirely from the b-jet "
              "(light stays central)");
        check(!approx_equal(ratio_bonly, 1.0),
              "(d) comb-only component changes the b-jet weight");
    }

    // ------------------------------------------------------------------
    // (e) An unsupported variation key must throw (the fixture comb systematic
    // category has no default, so correctionlib raises; the consumer rethrows
    // with the jet kinematics).
    // ------------------------------------------------------------------
    {
        bool did_throw = throws([&]() {
            run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.4f}, {1}, "valid",
                       "up_DOES_NOT_EXIST", "central");
        });
        check(did_throw, "(e) unsupported variation key throws");
    }

    // ------------------------------------------------------------------
    // (f) Jet passing the TIGHTEST WP (XXT). The payload thresholds
    // (tightest -> loosest) are {XXT:0.9, XT:0.7, T:0.5, M:0.3, L:0.1}; a
    // score of 0.95 >= 0.9 passes XXT, so `passed == 0` and the algebra
    // collapses to jet_w = (SF(XXT)*eff(XXT)) / eff(XXT) = SF(XXT) (the
    // efficiency cancels but is still evaluated/validated).
    // Flavor 5, "valid" regime, central comb SF/eff (from
    // make_btag_sf_strict_fixtures.py):
    //   SF(XXT) = COMB_BASE[5]["XXT"] + delta["central"] = 0.80 + 0 = 0.80
    //   eff(XXT) = EFF_VALID[5]["XXT"] = 0.10 (> 0, so no throw)
    //   jet_w = SF(XXT) = 0.80
    // ------------------------------------------------------------------
    {
        double w = run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.95f}, {1}, "valid",
                              "central", "central");
        check(approx_equal(w, 0.80),
              "(f) tightest-WP pass reproduces hand-computed SF(XXT) == 0.80");
    }

    // ------------------------------------------------------------------
    // (g) Jet failing ALL WPs: score 0.05 < loosest threshold L (0.1), so
    // `passed == thresholds.size()` and the algebra uses the
    // untagged-probability branch:
    //     jet_w = (1 - SF(L)*eff(L)) / (1 - eff(L))
    // Flavor 5, "valid" regime, central comb SF/eff:
    //   SF(L) = COMB_BASE[5]["L"] + delta["central"] = 0.98 + 0 = 0.98
    //   eff(L) = EFF_VALID[5]["L"] = 0.80
    //   jet_w = (1 - 0.98*0.80) / (1 - 0.80)
    //         = (1 - 0.784) / 0.20 = 0.216 / 0.20 = 1.08
    // ------------------------------------------------------------------
    {
        double w = run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.05f}, {1}, "valid",
                              "central", "central");
        check(approx_equal(w, 1.08),
              "(g) fails-all-WPs reproduces hand-computed "
              "(1-SF(L)*eff(L))/(1-eff(L)) == 1.08");
    }

    // ------------------------------------------------------------------
    // (h) An efficiency > 1 must throw as loudly as one <= 0. The "above_one"
    // regime sets flavor-5 eff(M) = 1.5.
    // ------------------------------------------------------------------
    {
        bool did_throw = throws([&]() {
            run_weight(mgr, {50.0f}, {1.0f}, {5}, {0.4f}, {1}, "above_one",
                       "central", "central");
        });
        check(did_throw, "(h) efficiency > 1 throws");
    }

    // ------------------------------------------------------------------
    // (i) A hadron flavor outside {0, 4, 5} has no per-flavor correction to
    // dispatch to, so it must throw rather than be silently skipped.
    // ------------------------------------------------------------------
    {
        bool did_throw = throws([&]() {
            run_weight(mgr, {50.0f}, {1.0f}, {3}, {0.4f}, {1}, "valid",
                       "central", "central");
        });
        check(did_throw, "(i) unknown jet flavor throws");
    }

    if (g_failures > 0) {
        std::cerr << g_failures << " case(s) FAILED" << std::endl;
        return 1;
    }
    std::cout << "All strict UParTAK4 b-tag cases PASSED." << std::endl;
    return 0;
}
